### ISSUE TITLE
Use 32 bit Msys2 to workaround Tea CI bug

### ISSUE THREAD

**Issue by fracting** [jhasse/pwcalculator#1]
Thanks for using Tea CI!

Just noticed 64 bit Msys2 fails for your build, sorry about that, you could use 32 bit as a workaround: https://github.com/TeaCI/tea-ci/issues/11

**Comment by jhasse** [comment]
Thanks!

I think the remaining error is a Wine, Waf or Python bug I've also seen with Wine on my local Linux machine: https://tea-ci.org/jhasse/pwcalculator/7

**Comment by fracting** [comment]
Not sure what's wrong, I'll have a look (very very) later. Busy preparing for immigration visa, I'm very slow for everything else until November. :)

If you are able to debug deeper that would be great, other wise we will wait.

**Comment by jhasse** [comment]
Closing as Tea CI seems to be discontinued.
